QuanLyCuaHangTapHoa/Models/NhanVien.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyCuaHangTapHoa.Models
{
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.Orders = new HashSet<Order>();
            this.DoanhThuViews = new HashSet<DoanhThuView>();
        }

        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập họ và tên")]
        [StringLength(100, ErrorMessage = "Họ tên không được vượt quá 100 ký tự")]
        public string FullName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập email")]
        [EmailAddress(ErrorMessage = "Email không hợp lệ")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        public string Address { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? NgaySinh { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Mật khẩu phải có ít nhất 6 ký tự")]
        public string Password { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn chức vụ")]
        public int? MaChucVu { get; set; }

        public string Picture { get; set; }

        public bool? Sex { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        [Phone(ErrorMessage = "Số điện thoại không hợp lệ")]
        [StringLength(15, MinimumLength = 9, ErrorMessage = "Số điện thoại không hợp lệ")]
        public string Sdt { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime? NgayTao { get; set; }

        public virtual ChucVu ChucVu { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoanhThuView> DoanhThuViews { get; set; }
    }
}

QuanLyCuaHangTapHoa/Controllers/NhanVienController.cs
using QuanLyCuaHangTapHoa.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace QuanLyCuaHangTapHoa.Controllers
{
    public class NhanVienController : Controller
    {
        quantaphoaEntities _db = new quantaphoaEntities();
        // GET: NhanVien
        public ActionResult Index(string searchString)
        {
            NhanVien nv = (NhanVien)Session["NV"];
            if (nv.MaChucVu == 1)
            {
                return RedirectToAction("Index", "Home");
            }
            var dsNhanVien = (from s in _db.NhanViens select s).ToList();
            // Tìm kiếm nhân viên trong quản lí nhân viên
            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                ViewBag.NhanVien = dsNhanVien.Where(s => s.FullName.ToLower().Contains(searchString)).ToList();
            }
            else
            {
                ViewBag.NhanVien = dsNhanVien;
            }
            return View();
        }
        // Thêm nhân viên mới 
        public ActionResult Create()
        {
            ViewBag.MaChucVu = new SelectList(_db.ChucVus, "MaChucVu", "ChucVu1");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NhanVien nhanvien, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                // Xử lý file upload
                if (file != null && file.ContentLength > 0)
                {
                    // Tạo đường dẫn lưu file
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Hinh/NhanVien"), fileName);
                    file.SaveAs(path);
                    nhanvien.Picture = fileName; // Lưu tên file vào thuộc tính Picture
                }
                _db.NhanViens.Add(nhanvien);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaChucVu = new SelectList(_db.ChucVus, "MaChucVu", "ChucVu1", nhanvien.MaChucVu);
            return View(nhanvien);
        }

        // Sửa thông tin nhân viên
        public ActionResult Edit(int id)
        {
            if (id.ToString() == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanvien = _db.NhanViens.Find(id);
            if (nhanvien == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaChucVu = new SelectList(_db.ChucVus, "MaChucVu", "ChucVu1", nhanvien.MaChucVu);
            return View(nhanvien);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FullName,Email,Address,NgaySinh,Password,MaChucVu,Picture,Sex,Sdt")] NhanVien nv, HttpPostedFileBase file)
        {

            NhanVien nhanvien = _db.NhanViens.Find(nv.Id);
            ViewBag.MaChucVu = new SelectList(_db.ChucVus, "MaChucVu", "ChucVu1", nhanvien.MaChucVu);
            if (ModelState.IsValid)
            {
                String anh = nhanvien.Picture;
                if (file != null)
                {
                    string pic = System.IO.Path.GetFileName(file.FileName);
                    String path = System.IO.Path.Combine(
                                           Server.MapPath("~/Hinh/NhanVien"), pic);
                    file.SaveAs(path);
                    anh = pic;
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }
                nhanvien.Picture = anh;
                nhanvien.FullName = nv.FullName;
                nhanvien.Email = nv.Email;
                nhanvien.Address = nv.Address;
                if (nv.NgaySinh != null)
                {
                    nhanvien.NgaySinh = nv.NgaySinh;
                }
                else
                {
                    nhanvien.NgaySinh = nhanvien.NgaySinh;
                }

                nhanvien.Password = nv.Password;
                nhanvien.MaChucVu = nv.MaChucVu;
                nhanvien.Sex = nv.Sex;
                nhanvien.Sdt = nv.Sdt;
                _db.Entry(nhanvien).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nv);

        }
        //Xóa nhân viên 
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanvien = _db.NhanViens.Find(id);
            if (nhanvien == null)
            {
                return HttpNotFound();
            }
            return View(nhanvien);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int Id)
        {
            NhanVien nhanvien = _db.NhanViens.Find(Id);
            _db.NhanViens.Remove(nhanvien);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


        // Xem chi tiết Nhân viên
        public ActionResult Detail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = _db.NhanViens
                .AsNoTracking()
                .Include(n => n.ChucVu)
                .FirstOrDefault(n => n.Id == id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }
    }
}

QuanLyCuaHangTapHoa/Views/NhanVien/Create.cshtml
@model QuanLyCuaHangTapHoa.Models.NhanVien

@{
    ViewBag.Title = "Thêm nhân viên mới";
    Layout = "~/Views/Shared/_layoutadmin.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <title>Thêm Nhân Viên Mới</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        @using (Html.BeginForm("Create", "NhanVien", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="page-header">
                <h1 class="page-title">
                    <i class="fas fa-plus-circle"></i>
                    Thêm Nhân Viên Mới
                </h1>
            </div>

            <div class="form-card">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.FullName, "Họ và Tên", new { @class = "control-label" })
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, "Email", new { @class = "control-label" })
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, "Mật Khẩu", new { @class = "control-label" })
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MaChucVu, "Chọn Chức Vụ", new { @class = "control-label" })
                    @Html.DropDownList("MaChucVu", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MaChucVu, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NgaySinh, "Ngày Sinh", new { @class = "control-label" })
                    @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @type = "date", @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, "Địa Chỉ Thường Trú", new { @class = "control-label" })
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Sdt, "Số Điện Thoại", new { @class = "control-label" })
                    @Html.EditorFor(model => model.Sdt, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sdt, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label class="control-label">Giới tính</label>
                    <div class="gender-select">
                        <label class="gender-option">
                            @Html.RadioButtonFor(model => model.Sex, true, new { @id = "male" })
                            <span class="gender-badge male">
                                <i class="fas fa-mars"></i>
                                Nam
                            </span>
                        </label>
                        <label class="gender-option">
                            @Html.RadioButtonFor(model => model.Sex, false, new { @id = "female" })
                            <span class="gender-badge female">
                                <i class="fas fa-venus"></i>
                                Nữ
                            </span>
                        </label>
                    </div>
                    @Html.ValidationMessageFor(model => model.Sex, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <label class="control-label">Ảnh Nhân Viên</label>
                    <div class="image-upload-container">
                        <div class="image-preview" id="imagePreview">
                            <div class="image-preview-placeholder">
                                <i class="fas fa-image fa-2x"></i>
                                <p>Xem trước ảnh</p>
                            </div>
                        </div>
                        <label for="file" class="custom-file-upload">
                            <i class="fas fa-cloud-upload-alt"></i>
                            Chọn Ảnh
                        </label>
                        <input type="file" name="file" id="file" accept="image/*" />
                        <div class="selected-file-name" id="fileName"></div>
                        @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="button-group">
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-save"></i>
                        Tạo Nhân Viên
                    </button>
                    <a href="@Url.Action("Index", "NhanVien")" class="btn btn-secondary">
                        <i class="fas fa-arrow-left"></i>
                        Hủy Bỏ
                    </a>
                </div>
            </div>
        }
    </div>

    <script>
        document.getElementById('file').addEventListener('change', function (e) {
            const file = e.target.files[0];
            const preview = document.getElementById('imagePreview');
            const fileName = document.getElementById('fileName');

            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    preview.innerHTML = `<img src="${e.target.result}" alt="Preview">`;
                }
                reader.readAsDataURL(file);
                fileName.textContent = file.name;
            } else {
                preview.innerHTML = `
                            <div class="image-preview-placeholder">
                                <i class="fas fa-image fa-2x"></i>
                                <p>Xem trước ảnh</p>
                            </div>`;
                fileName.textContent = '';
            }
        });
    </script>
</body>
</html>


<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'Segoe UI', system-ui, sans-serif;
    }

    body {
        background: linear-gradient(135deg, #f6fff8 0%, #f1fff5 100%);
        min-height: 100vh;
        padding: 2rem;
    }

    .container {
        max-width: 800px;
        margin: 0 auto;
    }

    .form-card {
        background: white;
        border-radius: 1rem;
        padding: 2rem;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        margin-top: 2rem;
    }

    .page-header {
        background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%);
        padding: 2rem;
        border-radius: 1rem;
        margin-bottom: 2rem;
        color: white;
    }

    .page-title {
        font-size: 1.8rem;
        font-weight: 700;
        margin-bottom: 1rem;
        display: flex;
        align-items: center;
        gap: 0.75rem;
    }

    .form-group {
        margin-bottom: 1.5rem;
    }

    .control-label {
        display: block;
        margin-bottom: 0.5rem;
        font-weight: 600;
        color: #1e293b;
    }

    .form-control {
        width: 100%;
        padding: 0.75rem;
        border: 1px solid #e2e8f0;
        border-radius: 0.5rem;
        font-size: 1rem;
        transition: all 0.3s ease;
        text-align: left;
    }

        .form-control:focus {
            outline: none;
            border-color: #22c55e;
            box-shadow: 0 0 0 3px rgba(34, 197, 94, 0.1);
        }

    select.form-control {
        padding-left: 0.75rem;
        background-position: right 0.75rem center;
        appearance: none;
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' fill='%234B5563' viewBox='0 0 16 16'%3E%3Cpath d='M8 11.5l-5-5h10l-5 5z'/%3E%3C/svg%3E");
        background-repeat: no-repeat;
        padding-right: 2.5rem;
    }

    .text-danger {
        color: #ef4444;
        font-size: 0.875rem;
        margin-top: 0.25rem;
    }

    .btn {
        display: inline-flex;
        align-items: center;
        gap: 0.5rem;
        padding: 0.75rem 1.5rem;
        border-radius: 0.5rem;
        font-weight: 600;
        text-decoration: none;
        transition: all 0.3s ease;
        border: none;
        cursor: pointer;
    }

    .btn-primary {
        background: #22c55e;
        color: white;
    }

        .btn-primary:hover {
            background: #16a34a;
            transform: translateY(-1px);
        }

    .btn-secondary {
        background: #67809f;
        color: #475569;
    }

        .btn-secondary:hover {
            background: #c2f970;
        }

    .button-group {
        display: flex;
        gap: 1rem;
        margin-top: 2rem;
    }

    .gender-select {
        display: flex;
        gap: 1rem;
        margin-top: 0.5rem;
    }

    .gender-option {
        cursor: pointer;
    }

        .gender-option input[type="radio"] {
            display: none;
        }

    .gender-badge {
        display: inline-flex;
        align-items: center;
        gap: 0.5rem;
        padding: 0.5rem 1rem;
        border-radius: 9999px;
        font-size: 0.875rem;
        font-weight: 500;
        transition: all 0.3s ease;
        border: 2px solid transparent;
    }

        .gender-badge.male {
            background: #f0fdf4;
            color: #16a34a;
        }

        .gender-badge.female {
            background: #fef2f2;
            color: #dc2626;
        }

    .gender-option input[type="radio"]:checked + .gender-badge.male {
        background: #dcfce7;
        border-color: #16a34a;
        box-shadow: 0 0 0 3px rgba(22, 163, 74, 0.1);
    }

    .gender-option input[type="radio"]:checked + .gender-badge.female {
        background: #fee2e2;
        border-color: #dc2626;
        box-shadow: 0 0 0 3px rgba(220, 38, 38, 0.1);
    }

    .gender-badge i {
        font-size: 1rem;
    }

    .gender-option:hover .gender-badge.male {
        background: #dcfce7;
    }

    .gender-option:hover .gender-badge.female {
        background: #fee2e2;
    }

    /* Styles cho phần upload ảnh */
    .image-upload-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        gap: 1rem;
        margin-top: 1rem;
    }

    .image-preview {
        width: 200px;
        height: 200px;
        border: 2px dashed #e2e8f0;
        border-radius: 1rem;
        display: flex;
        align-items: center;
        justify-content: center;
        overflow: hidden;
        position: relative;
        background: #f8fafc;
        transition: all 0.3s ease;
    }

        .image-preview:hover {
            border-color: #22c55e;
        }

        .image-preview img {
            max-width: 100%;
            max-height: 100%;
            object-fit: cover;
        }

    .image-preview-placeholder {
        color: #94a3b8;
        text-align: center;
        padding: 1rem;
    }

        .image-preview-placeholder i {
            font-size: 2.5rem;
            margin-bottom: 0.5rem;
        }

    .custom-file-upload {
        display: inline-flex;
        align-items: center;
        gap: 0.5rem;
        padding: 0.75rem 1.5rem;
        background: #22c55e;
        color: white;
        border-radius: 0.5rem;
        cursor: pointer;
        transition: all 0.3s ease;
        font-weight: 600;
    }

        .custom-file-upload:hover {
            background: #16a34a;
            transform: translateY(-1px);
        }

        .custom-file-upload i {
            font-size: 1.1rem;
        }

    #file {
        display: none;
    }

    .selected-file-name {
        margin-top: 0.5rem;
        color: #64748b;
        font-size: 0.875rem;
        text-align: center;
        max-width: 200px;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    /* Additional Styles for Better Form Layout */
    input[type="date"].form-control {
        text-align: left;
        padding-right: 0.75rem;
    }

    input[type="radio"] {
        width: 1rem;
        height: 1rem;
        margin-right: 0.5rem;
        cursor: pointer;
    }

    /* Responsive Adjustments */
    @@media (max-width: 640px) {
        body {
            padding: 1rem;
        }

        .form-card {
            padding: 1.5rem;
        }

        .button-group {
            flex-direction: column;
        }

        .btn {
            width: 100%;
            justify-content: center;
        }
    }
</style>

QuanLyCuaHangTapHoa/Views/NhanVien/Delete.cshtml
@model QuanLyCuaHangTapHoa.Models.NhanVien
@{
    ViewBag.Title = "Xóa Nhân Viên";
    Layout = "~/Views/Shared/_layoutadmin.cshtml";
}

<div class="delete-container">
    <div class="delete-card">
        <div class="delete-icon">
            <i class="fas fa-user-times"></i>
        </div>

        <div class="delete-content">
            <h2 class="delete-title">Xác nhận xóa nhân viên</h2>
            <p class="delete-text">Bạn có chắc chắn muốn xóa nhân viên:</p>

            <div class="employee-info">
                <div class="employee-avatar">
                    @if (string.IsNullOrEmpty(Model.Picture))
                    {
                        <img src="~/Hinh/user.jpg" alt="@Model.FullName" />
                    }
                    else
                    {
                        <img src="~/Hinh/NhanVien/@Model.Picture" alt="@Model.FullName" />
                    }
                </div>
                <div class="employee-details">
                    <h3 class="employee-name">@Model.FullName</h3>
                    <p class="employee-position">@Model.ChucVu.ChucVu1</p>
                </div>
            </div>

            <div class="delete-warning">
                <i class="fas fa-exclamation-triangle"></i>
                <p>Hành động này không thể hoàn tác. Tất cả dữ liệu liên quan sẽ bị xóa vĩnh viễn.</p>
            </div>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="button-group">
                    <button type="submit" class="btn btn-delete">
                        <i class="fas fa-trash-alt"></i>
                        Xác nhận xóa
                    </button>
                    <a href="@Url.Action("Index", "NhanVien")" class="btn btn-cancel">
                        <i class="fas fa-times"></i>
                        Hủy bỏ
                    </a>
                </div>
            }
        </div>
    </div>
</div>

<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    .delete-container {
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        padding: 2rem;
        background: linear-gradient(135deg, #f6fff8 0%, #f1f5f9 100%);
    }

    .delete-card {
        background: white;
        border-radius: 1.5rem;
        box-shadow: 0 20px 25px -5px rgba(34, 197, 94, 0.1), 0 10px 10px -5px rgba(34, 197, 94, 0.04);
        overflow: hidden;
        max-width: 600px;
        width: 100%;
        position: relative;
    }

    .delete-icon {
        background: linear-gradient(135deg, #22c55e 0%, #16a34a 100%);
        color: white;
        font-size: 3rem;
        height: 120px;
        display: flex;
        align-items: center;
        justify-content: center;
        position: relative;
    }

        .delete-icon::after {
            content: '';
            position: absolute;
            bottom: -20px;
            left: 50%;
            transform: translateX(-50%);
            border-left: 20px solid transparent;
            border-right: 20px solid transparent;
            border-top: 20px solid #16a34a;
        }

    .delete-content {
        padding: 2.5rem 2rem 2rem;
    }

    .delete-title {
        color: #1e293b;
        font-size: 1.5rem;
        font-weight: 700;
        text-align: center;
        margin-bottom: 1rem;
    }

    .delete-text {
        color: #475569;
        text-align: center;
        margin-bottom: 1.5rem;
    }

    .employee-info {
        display: flex;
        align-items: center;
        gap: 1.5rem;
        background: #f8fafc;
        padding: 1.5rem;
        border-radius: 1rem;
        margin-bottom: 1.5rem;
    }

    .employee-avatar {
        width: 80px;
        height: 80px;
        border-radius: 50%;
        overflow: hidden;
        border: 3px solid #22c55e;
    }

        .employee-avatar img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

    .employee-details {
        flex: 1;
    }

    .employee-name {
        color: #1e293b;
        font-size: 1.25rem;
        font-weight: 600;
        margin-bottom: 0.25rem;
    }

    .employee-position {
        color: #64748b;
        font-size: 0.875rem;
    }

    .delete-warning {
        display: flex;
        align-items: flex-start;
        gap: 1rem;
        padding: 1rem;
        background: #fef2f2;
        border-radius: 0.5rem;
        margin-bottom: 1.5rem;
    }

        .delete-warning i {
            color: #dc2626;
            font-size: 1.25rem;
        }

        .delete-warning p {
            color: #991b1b;
            font-size: 0.875rem;
            line-height: 1.5;
        }

    .button-group {
        display: flex;
        gap: 1rem;
        justify-content: center;
    }

    .btn {
        display: inline-flex;
        align-items: center;
        gap: 0.5rem;
        padding: 0.75rem 1.5rem;
        border-radius: 0.5rem;
        font-weight: 600;
        text-decoration: none;
        transition: all 0.3s ease;
        border: none;
        cursor: pointer;
    }

    .btn-delete {
        background: #dc2626;
        color: white;
    }

        .btn-delete:hover {
            background: #b91c1c;
            transform: translateY(-1px);
        }

    .btn-cancel {
        background: #e2e8f0;
        color: #475569;
    }

        .btn-cancel:hover {
            background: #f1f5f9;
        }

    /* Responsive Design */
    @@media (max-width: 640px) {
        .delete-container {
            padding: 1rem;
        }

        .delete-content {
            padding: 1.5rem 1rem;
        }

        .employee-info {
            flex-direction: column;
            text-align: center;
        }

        .button-group {
            flex-direction: column;
        }

        .btn {
            width: 100%;
            justify-content: center;
        }
    }
</style>